################################
## Airflow Result Backend Secret
#################################
{{- if (and .Values.data.resultBackendConnection (not .Values.data.resultBackendSecretName)) }}
{{- $host := .Values.data.resultBackendConnection.host | default (printf "%s-%s" .Release.Name "postgresql") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-result-backend
  labels:
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "db+postgresql://%s:%s@%s:%s/%s" .Values.data.resultBackendConnection.user .Values.data.resultBackendConnection.pass (ternary (printf "%s-%s" .Release.Name "pgbouncer") $host .Values.pgbouncer.enabled) ((ternary .Values.ports.pgbouncer .Values.data.resultBackendConnection.port .Values.pgbouncer.enabled) | toString) (ternary (printf "%s-%s" .Release.Name "result-backend") .Values.data.resultBackendConnection.db .Values.pgbouncer.enabled)) | b64enc | quote }}
{{- end }}
