################################
## Airflow Create User Job
#################################
{{- if .Values.webserver.defaultUser.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-create-user
  labels:
    tier: airflow
    component: create-user-job
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        tier: airflow
        component: create-user-job
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-user
          image: {{ template "airflow_image" . }}
          args:
            - "airflow"
            - "create_user"
            - "-r"
            - {{ .Values.webserver.defaultUser.role }}
            - "-u"
            - {{ .Values.webserver.defaultUser.username }}
            - "-e"
            - {{ .Values.webserver.defaultUser.email }}
            - "-f"
            - {{ .Values.webserver.defaultUser.firstName }}
            - "-l"
            - {{ .Values.webserver.defaultUser.lastName }}
            - "-p"
            - {{ .Values.webserver.defaultUser.password }}
          env:
          {{- include "custom_airflow_environment" . | indent 10 }}
          {{- include "standard_airflow_environment" . | indent 10 }}
          volumeMounts:
            - name: config
              mountPath: {{ template "airflow_config_path" . }}
              subPath: airflow.cfg
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "airflow_config" . }}
{{- end }}
