astronomer:
  houston:
    config:
      deployments:
        astroUnit:
          price: 10
        components:
        - au:
            default: 10
            limit: 100
          name: scheduler
        - au:
            default: 5
            limit: 100
          name: webserver
        - au:
            default: 2
            limit: 30
          name: statsd
        - au:
            default: 2
            limit: 2
          name: pgbouncer
        - au:
            default: 2
            limit: 2
          name: flower
        - au:
            default: 2
            limit: 2
          name: redis
        - au:
            default: 10
            limit: 100
          extra:
          - default: 600
            limit: 36000
            name: terminationGracePeriodSeconds
          - default: 1
            limit: 20
            name: replicas
          name: workers
        helm:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: astronomer.io/multi-tenant
                    operator: In
                    values:
                    - "true"
          pgbouncer:
            resultBackendPoolSize: 10
          webserver:
            failureThreshold: 60
            initialDelaySeconds: 15
            periodSeconds: 8
            timeoutSeconds: 30
          workers:
            resources:
              limits:
                ephemeral-storage: 10Gi
              requests:
                ephemeral-storage: 1Gi
        maxExtraAu: 1000
        maxPodAu: 100
        namespaceLabels:
          istio-injection: enabled
        sidecars:
          cpu: 400
          memory: 248
      publicSignups: false
    env:
    - name: AUTH__LOCAL__ENABLED
      value: "true"
  orbit:
    env:
    - name: ANALYTICS_TRACKING_ID
      value: tH2XzkxCDpdC8Jvn8YroJ
  registry:
    gcs:
      bucket: dev-astronomer-cloud-dev-236021-registry
      enabled: true
global:
  baseDomain: dev.steven-google-development.com
  deploymentNodePool:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: astronomer.io/multi-tenant
              operator: In
              values:
              - "true"
  istioEnabled: true
  platformNodePool:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: astronomer.io/multi-tenant
              operator: In
              values:
              - "false"
    tolerations:
    - effect: NoSchedule
      key: platform
      operator: Equal
      value: "true"
  tlsSecret: astronomer-tls
nginx:
  loadBalancerIP: 35.194.75.1
  perserveSourceIP: true
  privateLoadBalancer: false
prometheus:
  resources:
    limits:
      cpu: 2000m
      memory: 16Gi
    requests:
      cpu: 1000m
      memory: 4Gi

