images:
  airflow:
    repository: registry.dev.steven-google-development.com/ancient-intensity-9544/airflow
    tag: cli-8
executor: KnativeExecutor
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: astronomer.io/multi-tenant
          operator: In
          values:
          - "true"
airflowVersion: 1.10.5
allowPodLaunching: true
data:
  metadataConnection:
    db: ancient_intensity_9544_airflow
    host: pg-sqlproxy-gcloud-sqlproxy.astronomer
    pass: 3M39bs8MZkFwfxo0FRNgxXRsUEDoWfpH
    port: "5432"
    user: ancient_intensity_9544_airflow
  resultBackendConnection:
    database: astronomer_houston
    db: ancient_intensity_9544_airflow
    host: pg-sqlproxy-gcloud-sqlproxy.astronomer
    pass: rQqM956R1RJnpPB33eJp2tY9E53x3PPt
    password: ytV7sItq
    port: "5432"
    user: ancient_intensity_9544_celery
defaultAirflowVersion: 1.10.5
elasticsearch:
  connection:
    host: astronomer-elasticsearch-nginx.astronomer
    pass: 4221d08b8e2532705af7d0a8840bbe5e
    port: 9200
    user: ancient-intensity-9544
  enabled: true
flower:
  resources:
    limits:
      cpu: 200m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi
ingress:
  baseDomain: dev.steven-google-development.com
  class: astronomer-nginx
  enabled: true
limits:
- max:
    cpu: 10000m
    memory: 38400Mi
  type: Pod
- default:
    cpu: 100m
    memory: 384Mi
  defaultRequest:
    cpu: 100m
    memory: 384Mi
  type: Container
networkPolicies:
  enabled: true
pgbouncer:
  enabled: true
  maxClientConn: 2495
  metadataPoolSize: 249
  resources:
    limits:
      cpu: 200m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi
  resultBackendPoolSize: 10
platform:
  namespace: astronomer
  release: astronomer
  singleNamespace: false
  workspace: ck2mb14fc00an0902cqqi0dyu
privateRegistry:
  enabled: false
  repository: null
quotas:
  limits.cpu: 55400m
  limits.ephemeral-storage: 50Gi
  limits.memory: 202432Mi
  pods: 488
  requests.cpu: 55400m
  requests.ephemeral-storage: 50Gi
  requests.memory: 202432Mi
rbacEnabled: true
redis:
  resources:
    limits:
      cpu: 200m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi
registry:
  connection:
    email: admin@dev.steven-google-development.com
    host: registry.dev.steven-google-development.com
    pass: ced657594f9390e8f7a6ccd84a2fb09e
    user: ancient-intensity-9544
scheduler:
  resources:
    limits:
      cpu: 2000m
      ephemeral-storage: 3Gi
      memory: 5840Mi
    requests:
      cpu: 2000m
      ephemeral-storage: 2Gi
      memory: 5840Mi
secret: []
statsd:
  resources:
    limits:
      cpu: 200m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi
webserver:
  failureThreshold: 60
  initialDelaySeconds: 15
  jwtSigningCertificateSecretName: astronomer-houston-jwt-signing-certificate
  periodSeconds: 8
  resources:
    limits:
      cpu: 500m
      ephemeral-storage: 2Gi
      memory: 1920Mi
    requests:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 1920Mi
  timeoutSeconds: 30
workers:
  persistence:
    enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      ephemeral-storage: 10Gi
      memory: 3840Mi
    requests:
      cpu: 1000m
      ephemeral-storage: 1Gi
      memory: 3840Mi
  terminationGracePeriodSeconds: 600

