################################
## Airflow Scheduler ServiceAccount
#################################
{{- if .Values.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-knative-serviceaccount
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- if or .Values.registry.secretName .Values.registry.connection }}
imagePullSecrets:
  - name: {{ template "registry_secret" . }}
{{- end }}
{{- end }}
