################################
## Astronomer Houston ConfigMap
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-houston-config
  labels:
    component: houston
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  # These are system-specified config overrides.
  production.yaml: |
    webserver:
      port: {{ .Values.ports.houstonHTTP }}

    commander:
      enabled: true
      host: {{ .Release.Name }}-commander

    orbit:
      port: 80

    email:
      smtpUrl: ~

    auth:
      local:
        enabled: false

      openidConnect:
        auth0:
          enabled: false
          clientId: "rH2L4yKctlepniTyJW3MkuXuTreOHHn1"
          baseDomain: "astronomerio.auth0.com"

        google:
          enabled: true
          clientId: ~

      github:
        enabled: true

    helm:
      baseDomain: {{ .Values.global.baseDomain }}
      registryAuthSecret: {{ .Values.registry.auth.secretName }}
      releaseName: {{ .Release.Name }}
      releaseNamespace: {{ .Release.Namespace }}
      releaseVersion: {{ .Chart.Version }}
      singleNamespace: {{ .Values.global.singleNamespace }}

    # Airflow deployment configuration
    deployments:
      # Kubernetes labels to add on each airflow deployment namespace
      namespaceLabels:
        platform-release: {{ .Release.Name }}

      # These values get passed directly into the airflow helm deployments
      helm:
        # Default airflow version to deploy. This is templated into the default image tag.
        defaultAirflowVersion: "1.10.5"

        # Webserver configuration.
        webserver:
          # This is the name of the secret that gets copied from the platform namespace
          # to the airflow namespaces.
          jwtSigningCertificateSecretName: {{ template "houston.jwtCertificateSecret" . }}
          resources:
            limits:
              # XXX: There is an alert configured to trigger when ephemeral storage reaches 
              # 1800000000 bytes (90% of the 2Gi limit). Be aware of this when modifying
              # ephemeral-storage limits.
              ephemeral-storage: "2Gi"
            requests:
              ephemeral-storage: "1Gi"

          defaultUser:
            enabled: false

        # Worker configuration (applies to Celery and Kubernetes task pods).
        workers:
          resources:
            limits:
              ephemeral-storage: "2Gi"
            requests:
              ephemeral-storage: "1Gi"

        # Scheduler configuration.
        scheduler:
          resources:
            limits:
              ephemeral-storage: "2Gi"
            requests:
              ephemeral-storage: "1Gi"

        # Default quotas for airflow deployments.
        quotas:
          requests.ephemeral-storage: "50Gi"
          limits.ephemeral-storage: "50Gi"

        # If a private registry configuration is specified, we also pass this through
        # to the airflow deployments.
        {{- if .Values.global.privateRegistry }}
        privateRegistry:
          enabled: {{ .Values.global.privateRegistry.enabled | default false }}
          repository: {{ .Values.global.privateRegistry.repository | default "" }}
        {{- end }}

        platform:
          namespace: {{ .Release.Namespace }}
          singleNamespace: {{ .Values.global.singleNamespace | default false }}

        # Disable the postgres subchart. The platform pass credentials down
        # from the platform configuration.
        postgresql:
          enabled: false

    # If we're in single namespace mode, we will also
    # skip the configuration for elasticsearch. Houston will fallback
    # to its default modes, which are false/disabled.
    # XXX: We may want to decouple these configurations from the
    # singleNamespace config. At the moment, this is a convenient
    # helper to require a minimal config change to run the platform in
    # single namespace mode. Fluentd requires a ClusterRole to
    # enrich logs with kubernetes metadata. In a single namespace environment,
    # we're likely not going to get a ClusterRole from admins.
    {{- if not .Values.global.singleNamespace }}
      elasticsearch:
        enabled: true
        connection:
          host: {{ printf "%s-elasticsearch-nginx.%s" .Release.Name .Release.Namespace }}
          port: 9200

    elasticsearch:
      enabled: true
      client:
        host: {{ printf "%s-elasticsearch:9200" .Release.Name }}
        log: error
    {{- end }}

    prometheus:
      enabled: true
      host: {{ printf "%s-prometheus" .Release.Name }}

  # These are any user-specified config overrides.
  local-production.yaml: |
{{ toYaml .Values.houston.config | indent 4 }}
