################################
## NGINX Elasticsearch ConfigMap
#################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx-es
  labels:
    component: nginx
    tier: {{ template "nginx-es.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  nginx.conf: |-
    worker_processes 1;
    events { worker_connections 1024; }
    error_log /dev/stdout info;

    http {
      access_log /dev/stdout;

      upstream elasticsearch {
        server {{ .Release.Name }}-elasticsearch.{{ .Release.Namespace }}:{{ .Values.common.ports.http }};
        keepalive 15;
      }

      server {
        listen 9200 ssl;
        proxy_http_version 1.1;
        {{- if not .Values.global.istioEnabled }}
        proxy_set_header Host $host;
        {{- end }}
        proxy_set_header Connection "Keep-Alive";
        proxy_set_header Proxy-Connection "Keep-Alive";
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;
        location /healthz {
            return 200;
        }

        location ~ ^/ {
          proxy_pass http://elasticsearch;
        }

        location = /_search {
          # This combined with disabling explicit index searching downstream
          # prevents any deployment from being able to query any other indexes.
          rewrite ^/(.*) /fluentd.$remote_user.*/$1 break;
          proxy_pass http://elasticsearch;
        }
      }
    }
  self-signed.conf:
    ssl_certificate {{ template "es.tlsCertificatePath" . }}/tls.crt;
    ssl_certificate_key {{ template "es.tlsCertificatePath" . }}/tls.key;
  ssl-params.conf:
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    ssl_dhparam /etc/nginx/snippets/dhparams.pem;
  dhparams.pem: |
    -----BEGIN DH PARAMETERS-----
    MBYCEQC2po4TNzm9CbcF2An5fdSDAgEC
    -----END DH PARAMETERS-----