################################
## NGINX Elasticsearch Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "nginx-es.fullname" . }}-nginx
  labels:
    tier: logging
    component: es-ingress-controller
    chart: {{ template "nginx-es.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    tier: {{ template "nginx-es.name" . }}
    component: es-ingress-controller
    release: {{ .Release.Name }}
  ports:
    - port: 9200
      targetPort: 9200
      name: https
