################################
## NGINX Elasticsearch Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ template "nginx-es.fullname" . }}-nginx
  labels:
    tier: {{ template "nginx-es.name" . }}
    component: es-ingress-controller
    chart: {{ template "nginx-es.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ template "nginx-es.name" . }}
      component: es-ingress-controller
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: {{ template "nginx-es.name" . }}
        component: es-ingress-controller
        release: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/nginx/nginx-es-configmap.yaml") . | sha256sum }}
    spec:
      nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-nginx-es
          image: {{ template "nginx-es.image" . }}
          imagePullPolicy: {{ .Values.images.nginx.pullPolicy }}
          resources: {{ toYaml .Values.nginx.resources | indent 12 }}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx
            - mountPath: /etc/nginx/ssl
              name: secret-volume
          ports:
            - name: https
              containerPort: 9200
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ .Release.Name }}-nginx-es
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-self-signed-volume
          configMap:
            name: {{ .Release.Name }}-nginx-es
            items:
              - key: self-signed.conf
                path: self-signed.conf
              - key: ssl-params.conf
                path: ssl-params.conf
              - key: dhparams.pem
                path: dhparams.pem
        - name: es-tls-certificate-volume
          secret:
            secretName: astronomer-houston-jwt-certificate
        - name: secret-volume
          secret:
            secretName: nginxsecret