{{- if eq .Values.executor "CeleryExecutor" }}
{{- if eq .Values.workers.keda.enabled true }}

apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{  .Release.Namespace }}
  labels:
    deploymentName: {{ .Release.Name }}-worker
spec:
  scaleTargetRef:
    deploymentName: {{ .Release.Name }}-worker
  pollingInterval: 2   # Optional. Default: 30 seconds
  cooldownPeriod: 5   # Optional. Default: 300 seconds
  maxReplicaCount: 10  # Optional. Default: 100
  triggers:
    - type: postgres
      metadata:
        connStr: AIRFLOW_CONN_AIRFLOW_DB
        query: "SELECT ceil(COUNT(*)::decimal / 10) FROM task_instance WHERE state='running' OR state='queued'"
---
{{- end }}
{{- end }}
